APPLICATION = Project0

BOARD = nucleo-f411re

USEMODULE += periph_gpio
USEMODULE += xtimer
USEMODULE += ztimer
USEMODULE += periph_pwm
USEMODULE += periph_timer
USEMODULE += periph_i2c

#FEATURES_PROVIDED += periph_adc
#EFATURES_PROVIDED += periph_dma
#FEATURES_PROVIDED += periph_i2c
#FEATURES_PROVIDED += periph_pwm
#FEATURES_PROVIDED += periph_rtc
#FEATURES_PROVIDED += periph_spi
#FEATURES_PROVIDED += periph_timer
#FEATURES_PROVIDED += periph_uart

USEMODULE += bmp280_i2c

RIOTBASE ?= $(CURDIR)/../..

DEVELHELP ?= 1

QUIET ?= 1

include $(RIOTBASE)/Makefile.include
